### ISSUE TITLE
Port to GTK3?

### ISSUE THREAD

**Issue by volomike** [jwintz/qchart.js#13]
Julien, is there a port of this for GTK3? Just as you discovered that QQuickWidget is a Canvas object that acts much like webkit Canvas, I'm wondering if such a thing is similar in GTK3? It would be great if I could do static charts using chart.js stuff on some GTK3 component.

**Comment by jwintz** [comment]
No I'm afraid not. Gtk is not as bound to JavaScript as QML is. I know Vala but no straightforward solution comes to my mind.
On 14 Sep 2015 6:57 pm, Mike McKee <notifications@github.com> wrote:Julien, is there a port of this for GTK3? Just as you discovered that QQuickWidget is a Canvas object that acts much like webkit Canvas, I'm wondering if such a thing is similar in GTK3?

**Comment by volomike** [comment]
Thanks. I guess I'll try and code something custom with SVG in GTK3, or find some project where someone did this.
