### ISSUE TITLE
QChart with Qt .5.5 inside a "Qt Quick application"

### ISSUE THREAD

**Issue by piervalli** [jwintz/qchart.js#21]
Dear, 
I create a new  "Qt Quick application" with the wizard of Qt Creator and copy your example (QChartGallery.qml), Qt does not recognizes the element "Chart".

QQmlApplicationEngine failed to load component
qrc:/main.qml:112 Chart is not a type

Have you a suggestions?
Thanks
My best Regards

**Comment by jwintz** [comment]
is QChart.js and the qmldir embedded into your resource file ?

**Comment by piervalli** [comment]
Dear,

I fixed when I put the Qchart.js and qmldir in the resouces file.
<RCC>
    <qresource prefix="/">
        <file>main.qml</file>
        <file>QChart.js</file>
        <file>qmldir</file>
        <file>QChartGallery.js</file>
        <file>QChart.qml</file>
    </qresource>
</RCC>

Thanks, 
I want suggest you that might be useful a simple project in the your repository.

My Best Regards

**Comment by jwintz** [comment]
You're welcome. I'll do both Qml and C+ samples when I'll move to charts.js 2.0.
