### ISSUE TITLE
Using qChart module simply 

### ISSUE THREAD

**Issue by educhene** [jwintz/qchart.js#4]
I want to use the jbCharts from a simple Qt Quick application.
I created a simple project. Ok
I download the chart.js-master package. Ok

I don't use Git, so I can't follow your Setup process you describe.

Could you explain the process to do to add your package in the simple project and how it can be recognized and used by import procedure like "import jbQuick.Charts 1.0" ?

Thanks in advance.

**Comment by Nymerea** [comment]
Hello,

It's easy.

It put .js file into js folder and I put qml file with other qml file.

In my main . qml I import javascript library like that : 
```
import QtQuick 2.0
import "."
import "./js/QChart.js"        as Charts
import "./js/QChartGallery.js" as ChartsData
```

And after, use this example for your graphic : https://github.com/jwintz/qchart.js/blob/master/QChartGallery.qml

**Comment by educhene** [comment]
Hello,

I try your process with a simple project Application Qt Quick created from Qt Creator workspace : 
1) Create new Application Qt Quick project : OK
2) Try to run the project : OK, HMI well displayed
3) Create js folder and add QChart.js and QChartGallery.js in it : OK
4) Copy files QChart.qml and QChartGallery.qml in the main folder project (with main.qml) : OK
5) In the main.qml file, I added the import library : 
import "."
import "./js/QChart.js"        as Charts
import "./js/QChartGallery.js" as ChartsData

6) PB : Then, if I compile and launch again my application (without adding any code), the HMI will not displayed and I have this error message in the Console QML/JS : qrc:/main.qml:7 Script qrc:/js/QChart.js unavailable qrc:/js/QChart.js:-1 File not found

Otherwise, If I use the Chart component in my main.qml file, the Qt Creator editor says : Unknown Component (M300).

Any Ideas ??

**Comment by Nymerea** [comment]
I don't where is your javascript's folder relative to your qml file.

The errors messages tell us he can't find the javascript file. maybe you should use 

```
import "."
import "js/QChart.js" as Charts
import "js/QChartGallery.js" as ChartsData
```

**Comment by educhene** [comment]
Sorry, but it doesn't work for me.
I try to copy manually the files under the compiled folder, then run the program under QtCreator : Same problem : 
`Début du débogage`
`QML debugging is enabled. Only use this in a safe environment.`
`QML Debugger: Waiting for connection on port 56769...`
`QQmlApplicationEngine failed to load component`
`qrc:/main.qml:7 Script qrc:/js/QChart.js unavailable`
`qrc:/js/QChart.js:-1 File not found`

With the development folder (source code), the javascript Qhart.js file is under the js folder : The compiler find it : the compilation is ok. But it doesn't work if I try to run the program.

Another problem : even if the compilation is ok, the Chart object under the QtCreator editor is unknown `(composant inconnu M300)`

**Remember** : I start with the simple project Application Qt Quick created from Qt Creator workspace, nothing else added, so very simple.

**Comment by jwintz** [comment]
Have you added the javascript components to a ressource file and compiled it with qrc ?

**Comment by cygnus2k** [comment]
I had the same error.
Solve it by copying the "jbQuick" folder to this folder in my installation path:
/opt/Qt5.6.0/5.6/android_armv7/qml/
