### ISSUE TITLE
Updating charts with dynamic data

### ISSUE THREAD

**Issue by ldanzinger** [jwintz/qchart.js#6]
I'm trying to use the pie chart and have some questions about updating the data displayed in it. I have a map and the user clicks on the map and data is summarized. I then want to update the pie chart. To do this, I am creating a property var pieData: [] at the top, and bind that to the chart_pie data property. I have a few problems:

- If I don't provide any initial data, nothing ever displays
- If I do provide some initial data (ex: property var pieData:[{value: 10, color: "grey"}]), then this does display. However, I want the chart to update whenever I click on the map. Each time I click, I update the pieData var, but nothing happens. I tried creating a signal and calling repaint whenever the property changes. The signal fires and the chart repaints, but it still uses the original data and not my updated data. Any suggestions? Is this meant to work with dynamically updating data?

**Comment by danieloneill** [comment]
Due to the way it's written you have to manually invalidate the chart before updating the data.

I do it like:
```
        console.log("Charting: "+JSON.stringify( chartData, null, 2 ));
        salesGraph.chartData = chartData;
        salesGraph.chart = false; // HACK. Force it to update.
        salesGraph.repaint();
```

Definitely a bug, though. All it needs is an "onGraphDataChanged" handler to update the 'graph' object.

**Comment by joshmarshall1995** [comment]
I am finding this a real issue.. daniel I tried the method that you described but to no avail. 
My chart, chartgallery and js pages are all separate I then call the chart in my main qml, it displays but no data gets updated.. this is my function:
    function updatechart(){
        chart.chartData = [CVCAM.showvalues()];
        chart.chartData = false;
        chart.repaint();
        console.log(CVCAM.showvalues(), chart.repaint(), "Repainting")
    }
any ideas why my charts not updating?

**Comment by danieloneill** [comment]
Josh, I'd add a "chart.chart = false;" in there and try again.

The offending code is https://github.com/jwintz/qchart.js/blob/master/QChart.qml#L39

If your chart object isn't destroyed or otherwise invalidated, the appropriate constructor (with your chartData as a parameter) is never called when onPaint happens.

**Comment by jwintz** [comment]
Give it another try. #9 may have solved the issue.

Thanks.

**Comment by ricnrng** [comment]
Try to call chart.update() before chart.repaint() .where chart is the object of your QChart class

**Comment by ldanzinger** [comment]
A bit late on this, but works for me now. Got it working with our mapping API for Qt (ArcGIS Runtime SDK for Qt). Pretty cool!

![screen shot 2016-02-26 at 3 07 34 pm](https://cloud.githubusercontent.com/assets/4107363/13367916/115069bc-dc9b-11e5-8fb5-8126c42b254e.png)
