### ISSUE TITLE
Please issue a release

### ISSUE THREAD

**Issue by zyga** [jwintz/qchart.js#7]
Hi

I'm working on a Debian an Ubuntu package for qtchart.js. For the monitoring of upstream releases (also known as debian/watch file) we need a location for a release tarball. It would be very useful if you could generate a release tarball (with an associated tag in the repository).

For your consideration, I'm also about to open two more issues about small debian patches we have that make everything work. I'll report them separately and link them here.

Thanks

**Comment by jwintz** [comment]
Thanks for your consideration. I will tag it as soon as we finish #10. Your help is much appreciated !
